import React, { useState } from 'react';
import api from '../api';

const QUICK = [
  'What are the graduation requirements?',
  'How does the warning system work?',
  'What are the semester phases?',
  'How do course reviews work?',
  'What is my current GPA?',
  'How does the waitlist work?',
  'What happens when a course is cancelled?',
  'How do instructor complaints work?',
];

export default function AIAssistant() {
  const [question, setQuestion] = useState('');
  const [answer, setAnswer] = useState('');
  const [source, setSource] = useState('');
  const [busy, setBusy] = useState(false);
  const [asked, setAsked] = useState('');

  const ask = async (q) => {
    const trimmed = (q || question).trim();
    if (!trimmed) return;
    setBusy(true); setAnswer(''); setSource(''); setAsked(trimmed);
    try {
      const r = await api.post('/ai', { question: trimmed });
      setAnswer(r.data.answer);
      setSource(r.data.source || 'local');
      setQuestion(trimmed);
    } catch {
      setAnswer('Sorry, something went wrong. Please try again.');
      setSource('local');
    } finally { setBusy(false); }
  };

  return (
    <>
      <div className="page-header">
        <h1>AI Assistant</h1>
        <p>Ask anything about College0 — policies, grades, phases, rules, and more.</p>
      </div>

      <div className="ai-card">
        <form onSubmit={e => { e.preventDefault(); ask(question); }}>
          <div className="form-group" style={{ marginBottom: 12 }}>
            <label>Your Question</label>
            <textarea
              value={question}
              onChange={e => setQuestion(e.target.value)}
              placeholder="e.g. What are the graduation requirements? How do I enroll in courses?"
              style={{ minHeight: 90 }}
            />
          </div>
          <div className="ai-btn-row">
            <button type="submit" className="btn-primary" disabled={busy || !question.trim()}>
              {busy ? 'Thinking…' : 'Ask AI'}
            </button>
            <button type="button" className="btn-secondary" onClick={() => { setQuestion(''); setAnswer(''); setSource(''); setAsked(''); }}>
              Clear
            </button>
          </div>
        </form>

        {answer && (
          <div className="ai-answer">
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 }}>
              <strong style={{ fontSize: '0.72rem', color: 'var(--muted)', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
                Answer
              </strong>
              {source === 'llm' ? (
                <span style={{
                  fontSize: '0.68rem', fontWeight: 700, padding: '2px 8px', borderRadius: 10,
                  background: '#fef3c7', color: '#92400e', border: '1px solid #fde68a',
                  display: 'flex', alignItems: 'center', gap: 4
                }}>
                  ⚠ AI Generated · May hallucinate
                </span>
              ) : (
                <span style={{
                  fontSize: '0.68rem', fontWeight: 700, padding: '2px 8px', borderRadius: 10,
                  background: '#f0fdf4', color: '#166534', border: '1px solid #bbf7d0',
                  display: 'flex', alignItems: 'center', gap: 4
                }}>
                  ✓ From knowledge base
                </span>
              )}
            </div>

            {source === 'llm' && (
              <div style={{
                fontSize: '0.75rem', background: '#fffbeb', border: '1px solid #fde68a',
                borderRadius: 6, padding: '8px 12px', marginBottom: 10, color: '#92400e', lineHeight: 1.5
              }}>
                <strong>Note:</strong> This answer was generated by an AI language model because no exact match was found
                in the College0 knowledge base. It may contain inaccuracies. Always verify important information with your
                registrar or course instructor.
              </div>
            )}

            <div style={{ fontSize: '0.88rem', lineHeight: 1.7 }}>{answer}</div>

            {asked && (
              <div style={{ marginTop: 10, fontSize: '0.72rem', color: 'var(--muted)', fontStyle: 'italic' }}>
                Asked: "{asked}"
              </div>
            )}
          </div>
        )}

        <div style={{ marginTop: 20 }}>
          <div style={{ fontSize: '0.78rem', fontWeight: 600, color: 'var(--muted)', marginBottom: 10 }}>
            Quick Questions:
          </div>
          <div className="quick-questions">
            {QUICK.map(q => (
              <button key={q} className="quick-btn" onClick={() => { setQuestion(q); ask(q); }}>
                {q}
              </button>
            ))}
          </div>
        </div>

        <div style={{ marginTop: 20, padding: '12px 14px', background: '#f8f9fb', borderRadius: 8, fontSize: '0.75rem', color: 'var(--muted)', lineHeight: 1.6 }}>
          <strong style={{ color: 'var(--text)' }}>How it works:</strong> Questions are first matched against the College0 knowledge base
          for precise, verified answers. If no match is found, the question is forwarded to an AI language model for a best-effort response
          (shown with a hallucination warning).
        </div>
      </div>
    </>
  );
}
